import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";

for (const file of ["index.html", "realtime.html", "tactics.html", "studio.html", "stages.html", "characters.html", "sprites.html"]) {
  const html = fs.readFileSync(new URL(file, import.meta.url), "utf8");
  assert.match(html, /^<!doctype html>/i, `${file}: standards mode`);
  for (const [, code] of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)) {
    if (code.trim()) new Function(code);
  }
}
for (const file of ["poop-config.js", "tactics-engine.js", "stage-loader.js"]) {
  new Function(fs.readFileSync(new URL(file, import.meta.url), "utf8"));
}

const realtime = fs.readFileSync(new URL("realtime.html", import.meta.url), "utf8");
const tacticsShell = fs.readFileSync(new URL("tactics.html", import.meta.url), "utf8");
const tacticsEngine = fs.readFileSync(new URL("tactics-engine.js", import.meta.url), "utf8");
const tactics = `${tacticsShell}
${tacticsEngine}`;
assert.ok(!realtime.includes("GSIZE"), "removed undefined realtime sprite constant");
assert.match(tactics, /newGame\(false\)/, "title screen must not advance turns");
assert.match(tactics, /POOPULATION_CONFIG\.tactics/, "tactics reads shared master data");
assert.match(tactics, /d\.dir>0 && a\.tx>d\.tx/, "back attack follows the corrected facing rule");
assert.match(tactics, /function nextStage\(\)/, "stage transition carries the live map forward");
assert.match(tactics, /function openCamp\(\)/, "stage clear opens a reward camp");
assert.match(tactics, /function chooseReward\(i\)/, "one reward advances to the next stage");
assert.match(tactics, /function clearStageIfReady\(\)/, "round survival uses one shared stage-clear check");
assert.match(tactics, /G\.round=Math\.min\(s\.rounds,G\.round\+1\)/, "round counter never displays beyond the current stage limit");
assert.match(tactics, /if\(clearStageIfReady\(\)\) return;/, "defeating the final enemy clears without another world tick");
assert.ok(!tactics.includes("G.round>LAST_ROUND"), "stage clear no longer waits for an extra round");
assert.match(tactics, /kind:"NEW GORILLA",type:"gorilla"/, "camp can unlock and recruit a gorilla type");
assert.match(tactics, /kind:"HERD ABILITY",type:"ability"/, "camp can unlock a herd ability");
assert.match(tactics, /kind:"PERMANENT BUFF",type:"upgrade"/, "camp can grant a permanent stat upgrade");
assert.match(tactics, /BORN\[c\]\.filter\(\(\[type\]\)=>G\.progress\.unlocked\.includes\(type\)\)/, "birth pool respects unlocked gorillas");
assert.match(tactics, /G\.stage<STAGE_COUNT&&s\.camp/, "stage JSON decides whether an intermission opens");
assert.match(tactics, /enemyStageStats/, "enemy stats scale by stage");
assert.match(tactics, /progress:\{unlocked:/, "run inventory is initialized with the starting roster");
assert.equal((tactics.match(/Math\.random/g)||[]).length,1,"randomness is cosmetic only");
assert.match(tactics, /T==="rocket"&&u\.belly\.length<poopNeed\(u\)/,"strong poop requires eaten fruit");
assert.match(tactics, /function poopNeed\(\)\{ return 1; \}/,"one eaten fruit always enables normal poop");
assert.match(tactics, /function poopKind\(u\)\{\s*if\(new Set\(u\.belly\)\.size>=3\) return "gold";\s*return "normal";/,"regular poop stays one-tile normal except for three-color gold");
assert.match(tactics, /if\(kind==="gold"\)\{\s*for\(const color of COLORS\)\{\s*const i=u\.belly\.indexOf\(color\);\s*if\(i>=0\) u\.belly\.splice\(i,1\);/,"gold poop consumes one fruit of every color");
assert.ok(!tactics.includes('id="forecastPanel"'),"deterministic forecast panel is removed from the battle UI");
assert.ok(!tactics.includes("音楽はオリジナル"),"opening screen omits meta commentary about the soundtrack");
assert.match(tactics, /const BELLY_MAX=3;/,"tactics belly has exactly three fruit slots");
assert.match(tactics, /u\.belly\.length>=BELLY_MAX/,"eating is disabled when all three belly slots are full");
assert.match(tactics, /if\(glut&&slots>=2&&t\.fruit>=1\)/,"glutton eating also respects remaining belly slots");
assert.match(tactics, /u\.belly=\[\.\.\.u\.belly,\.\.\.Array\(eaten\)\.fill\(t\.c\)\]/,"eating replaces only the active gorilla's fruit slots");
assert.match(tactics, /u\.buffs=\{\.\.\.u\.buffs\}/,"eating replaces only the active gorilla's fruit buffs");
assert.match(tactics, /id="bLang"/,"battle UI exposes a Japanese-English language switch");
assert.match(tactics, /localStorage\.setItem\("poopulation-lang",LANG\)/,"language preference persists");
assert.match(tactics, /ArrowLeft:\[-1,0\],ArrowRight:\[1,0\],ArrowUp:\[0,-1\],ArrowDown:\[0,1\]/,"arrow keys select movement tiles");
assert.match(tactics, /id="cv"[^>]*tabindex="0"[^>]*aria-keyshortcuts="ArrowLeft ArrowRight ArrowUp ArrowDown Space Enter"/,"battlefield is keyboard-focusable");
assert.match(tactics, /const confirmKey = e\.key===" "\|\|e\.code==="Space"/,"space confirms the keyboard tile cursor");
assert.match(tactics, /if\(G\.phase==="move"&&!G\.mode&&confirmKey\)\{[\s\S]{0,240}?doMove\(u,path,/,"space moves the gorilla onto the selected tile");
assert.match(tacticsShell, /<script src="tactics-engine\.js/, "battle shell loads the shared tactics engine");
assert.match(tacticsShell, /<script src="stage-loader\.js/, "battle shell loads JSON stage support");
assert.match(tacticsShell, /id="difficultySelect"/, "title screen exposes campaign difficulty");

/* ── Claude Design「POOPULATION UI」1c/1d/1e/1f のリニューアル ── */
assert.match(tacticsShell, /id="hudTopBar"[\s\S]*id="hudBottomBar"/, "1c: HUD is two floating bars, not panels");
assert.ok(!tacticsShell.includes('id="forestPanel"'), "1c drops the right-hand forest panel");
assert.match(tacticsShell, /id="intentBanner"/, "1c teaches the enemy-intent telegraph");
assert.match(tacticsShell, /#intentBanner\{[\s\S]*left:10px!important;right:10px!important;top:132px!important;transform:none!important;[\s\S]*grid-template-columns:auto minmax\(0,1fr\)/, "mobile enemy intent stays a compact horizontal banner");
assert.match(tacticsShell, /class="cmd poop" id="aPoop"/, "1c makes POOP the hero command");
assert.match(tacticsShell, /grid-template-columns:minmax\(0,1fr\) auto minmax\(0,1fr\)/, "command deck stays centered between symmetric side columns");
assert.match(tacticsShell, /\.cmd\{width:var\(--cmd-size\);height:var\(--cmd-size\);flex:0 0 var\(--cmd-size\)/, "every command card uses the same responsive square size");
assert.match(tacticsShell, /\.cmd \.cl\{[^}]*white-space:nowrap/, "command labels stay on one line");
assert.match(tacticsShell, /\.cmd \.ico\{width:var\(--cmd-icon\);height:var\(--cmd-icon\)/, "every command icon uses one shared optical slot");
assert.ok(!/\.cmd\.poop\{[^}]*(?:width|height):/.test(tacticsShell), "poop command cannot override the shared card size");
assert.match(tacticsShell, /id="roundPips"/, "1c shows rounds as pips");
assert.match(tacticsShell, /id="difficultySelect" role="radiogroup"/, "1d difficulty is a segmented control");
assert.match(tacticsShell, /class="chapter-name">第一章　うんちの目覚め</, "title leads with the correct first chapter name");
assert.ok(!tacticsShell.includes("MISSION DOCTRINE")&&!tacticsShell.includes("NO RANDOM"), "title omits design-manifesto copy");
assert.ok(!tacticsShell.includes('class="title-links"'), "title omits authoring and data-tool links");
assert.match(tacticsEngine, /if\(AC\.state!=="running"\) await AC\.resume\(\);[\s\S]*if\(run!==musicRun\|\|!snd\|\|BGMV<=0\) return;[\s\S]*musicTick\(\)/, "BGM waits for AudioContext resume before scheduling notes");
assert.match(tacticsShell, /id="campNextBody"/, "1e previews the next stage beside the rewards");
assert.match(tacticsShell, /id="cGrowth"/, "1f leads with fruit growth against its cap");
assert.match(tacticsShell, /id="cHerd"/, "1f lets you switch unit from the herd strip");

/* 人族の狙いは副作用なしで先読みし、実行と表示で同じ判断を使う */
assert.match(tacticsEngine, /function foePlan\(u\)/, "enemy AI decision is a pure planner");
assert.match(tacticsEngine, /function recomputeIntent\(\)/, "intent tiles are recomputed for the telegraph");
assert.match(tacticsEngine, /const plan=foePlan\(u\);/, "the enemy turn runs the same plan it telegraphed");
assert.match(tacticsEngine, /G\.intent&&G\.intent\.has\(k\)/, "targeted tiles are drawn on the board");
assert.match(tacticsEngine, /function cycleCard\(dir\)/, "Q and E cycle the unit detail");
assert.match(tacticsEngine, /function bellyPlan\(u\)/, "belly maps to the poop that comes out next");
assert.match(tacticsEngine, /function openCardFor\(u\)/, "opening the detail overlay is one explicit entry point");
assert.equal((tacticsEngine.match(/setState\(\{ui:"details"\}\)/g)||[]).length, 1,
  "only openCardFor opens the overlay, so drawing the card each turn cannot force it open");
assert.ok(!tacticsShell.includes("POOP_TACTICS_BOOT = "), "engine lives in tactics-engine.js, not inline");
assert.match(tactics, /function showTileHint\(x,y\)/,"hovered and keyboard-selected tiles share one detail panel");
assert.match(tactics, /L\("高さ","HEIGHT"\)/,"tile detail exposes terrain height in both languages");
assert.match(tactics, /L\("肥沃度","FERTILITY"\)/,"tile detail exposes fertility in both languages");
assert.ok(!/const label=u\.side==="ape"\?`▶ \$\{u\.name\} 行動中`/.test(tactics),"blur-prone active-unit canvas label is removed");
assert.match(tactics, /function captureStageStart\(\)/,"each stage records a restart checkpoint");
assert.match(tactics, /function restartStage\(\)/,"restart restores only the current stage checkpoint");
assert.ok(!tactics.includes('$("bReset").onclick=()=>{ start();'),"restart no longer wipes the entire run");
assert.ok(!/poopKind\(u\)[\s\S]{0,300}traits\.includes/.test(tactics),"traits do not replace the regular poop action");
assert.match(tactics, /sk:\{n:"ロケットうんち", c:5, d:"射程3/,"normal gorilla has a distinct ranged poop skill");
assert.match(tactics, /function dropPoop\(u,kind,c,tx=u\.tx,ty=u\.ty\)/,"poop can land on a selected tile");
assert.match(tactics, /actionPoop\(u,"big",tx,ty\)/,"normal skill fires big poop at its target");
assert.match(tactics, /if\(st\.behavior==="rocket"\)\{\s*const range=tilesInRange\(u\.tx,u\.ty,3\)/,"normal skill previews its range-three target area");
assert.match(tactics, /Math\.sin\(flight\*Math\.PI\)\*CFG\.arc\*1\.4/,"ranged poop follows a visible arc");
assert.match(tactics, /if\(t\.v<3\)\{\s*t\.v\+\+/,"wizard rain advances vegetation immediately");
assert.match(tactics, /if\(t\.fire>0\)\{ t\.fire=0; quenched\+\+;/,"wizard rain extinguishes without undoing its own growth");
assert.match(tactics, /r:\{jp:"こうげき",gain:2\}/,"red fruit raises attack");
assert.match(tactics, /b:\{jp:"最大MP",gain:2\}/,"blue fruit raises max MP");
assert.match(tactics, /y:\{jp:"すばやさ",gain:2\}/,"yellow fruit raises speed");
assert.ok(!tactics.includes("FRUIT_BUFF_CAP"),"fruit upgrades have no per-fruit count limit");
assert.match(tactics, /FRUIT_STAT_MAX=99/,"fruit-upgraded stats have a shared maximum");
assert.match(tactics, /Math\.min\(FRUIT_BUFF\[t\.c\]\.gain,Math\.max\(0,FRUIT_STAT_MAX-fruitStat\(u,t\.c\)\)\)/,"fruit upgrades clamp before applying");
assert.match(tactics, /if\(t\.c==="b"\) u\.maxmp\+=add/,"blue fruit updates the unit MP cap by the clamped amount");
assert.match(tactics, /big\s+:\{jp:"でかうんち",\s+fert:6, size:1\.7, splash:6/,"big poop fertilizes all five cross tiles equally");
assert.ok(!tactics.includes("wild"),"initial and poop-grown vegetation use the same rules");
assert.match(tactics, /treeAge:0/,"each tree tracks its own survival time");
assert.match(tactics, /if\(t\.v===3&&t\.fire<=0\) t\.treeAge\+\+;/,"surviving mature trees age with world growth");
assert.match(tactics, /t\.treeAge>=BIRTH_TREE_TURNS/,"birth comes directly from a long-surviving tree");
assert.match(tactics, /parent\.t\.treeAge=0/,"a parent tree restarts its birth timer after birth");
assert.match(tactics, /for\(let dy=-1;dy<=1;dy\+\+\)for\(let dx=-1;dx<=1;dx\+\+\)\{\s+const t=at\(A\.tx\+dx,A\.ty\+dy\)/,"rain animation covers every tile in its 3x3 area");
assert.match(tactics, /r===1 \? "前後左右 4マス"/,"range 1 is explained as four orthogonal tiles");
assert.match(tactics, /setRange\(range\)/,"the whole attack range is previewed");
assert.ok(!tactics.includes('.like'),"tactics has no favorite-fruit exception");
assert.ok(!realtime.includes('.like'),"realtime has no favorite-fruit exception");
assert.ok(!/return ["']wet["']/.test(tactics+realtime),"blue fruit no longer creates wet poop");
assert.match(tactics, /new Set\(u\.belly\)\.size>=3\) return "gold"/,"three colors still create gold poop in tactics");
assert.match(realtime, /new Set\(\[c,\.\.\.g\.belly\]\)\.size>=3\) return "gold"/,"three colors create gold poop in realtime");
assert.match(tactics, /12\+Math\.round\(K\.size\*6\)/,"poop landing has an amplified particle burst");
assert.match(realtime, /since<0\.45/,"poop landing draws a visible shockwave");

const sandbox = { window:{}, localStorage:{ getItem:()=>null } };
const configSource=fs.readFileSync(new URL("poop-config.js", import.meta.url), "utf8");
vm.runInNewContext(configSource, sandbox);
const master=sandbox.window.POOPULATION_CONFIG.tactics;
assert.ok(master.enemies.killer.atk < master.allies.normal.atk, "default killer is weaker than a normal gorilla");
assert.ok(master.startRoster.length>0 && master.waves.length>0, "fallback roster and waves remain playable");
assert.equal(master.allies.normal.rng,1,"normal gorilla attacks the four adjacent tiles");
assert.ok(master.birthTreeTurns>=1,"tree survival turns are master data");
assert.ok(master.waves.every(w=>w.r<=master.lastRound), "fallback waves fit inside the configured run");
const oldSandbox={window:{},localStorage:{getItem:()=>JSON.stringify({version:4,tactics:{stageCount:2}})}};
vm.runInNewContext(configSource,oldSandbox);
assert.equal(oldSandbox.window.POOPULATION_CONFIG.tactics.stageCount,4,"old two-stage saves migrate to the campaign baseline once");

const stageSandbox={globalThis:{}};
vm.runInNewContext(fs.readFileSync(new URL("stage-loader.js",import.meta.url),"utf8"),stageSandbox);
const stageApi=stageSandbox.globalThis.POOPULATION_STAGES;
const stageData=JSON.parse(fs.readFileSync(new URL("stages.json",import.meta.url),"utf8"));
assert.equal(stageData.campaign.chapters[0].name.ja,"第一章　うんちの目覚め","chapter one keeps the approved title");
assert.ok(!stageData.difficulties.some(d=>d.blurb.ja.includes("設計どおり")),"difficulty copy describes play instead of design intent");
const characterData=JSON.parse(fs.readFileSync(new URL("characters.json",import.meta.url),"utf8"));
const characterReport=stageApi.validateCharacters(characterData);
assert.equal(characterReport.errors.length,0,"character JSON passes schema validation");
const spriteData=JSON.parse(fs.readFileSync(new URL("sprites.json",import.meta.url),"utf8"));
const spriteReport=stageApi.validateSprites(spriteData);
assert.equal(spriteReport.errors.length,0,"sprite JSON passes schema validation");
const stageReport=stageApi.validate(stageData,{allyKinds:characterData.allies.map(c=>c.id),enemyKinds:characterData.enemies.map(c=>c.id)});
assert.equal(stageReport.errors.length,0,"stage JSON passes schema validation");
const normalCampaign=stageApi.resolve(stageData,"normal"), easyCampaign=stageApi.resolve(stageData,"easy");
assert.equal(normalCampaign.stages.length,24,"campaign contains 24 editable stages");
assert.equal(normalCampaign.targetPlayHours,30,"campaign records the 30-hour target");
assert.equal(normalCampaign.stages[0].rounds,4,"the first stage starts with only four rounds");
assert.ok(normalCampaign.stages.some(s=>s.terrain===null),"stages can inherit the live map");
assert.ok(normalCampaign.stages.some(s=>s.objective.type!=="survive"),"campaign uses multiple objective types");
assert.ok(easyCampaign.stages[0].rounds<normalCampaign.stages[0].rounds,"difficulty can shorten stages");
assert.ok(easyCampaign.stages.at(-1).enemyMul.hp<normalCampaign.stages.at(-1).enemyMul.hp,"difficulty scales enemy HP");
assert.match(tactics,/const CHARACTER_SET=window\.POOPULATION_CHARACTERS/,"tactics loads data-driven characters");
assert.match(tactics,/behavior:c\.skill\.behavior/,"new allies reuse skill behavior templates");
assert.match(tactics,/ai:c\.ai/,"new enemies reuse AI templates");
assert.match(tactics,/POOPULATION_SPRITES\?\.sprites/,"edited sprite JSON overrides built-in character art");
assert.match(tacticsShell,/API\.loadSprites\("sprites\.json"\)/,"tactics loads editable sprite data");
const spriteEditor=fs.readFileSync(new URL("sprites.html",import.meta.url),"utf8");
assert.match(spriteEditor,/id="grid"/,"sprite editor exposes a pixel grid");
assert.match(spriteEditor,/function encode\(\)/,"sprite editor exports palette-indexed pixels");
assert.match(spriteEditor,/function reduceColors\(rows,preferred=""\)/,"sprite editor keeps output within the 16-color limit");
assert.match(spriteEditor,/id="palette"/,"sprite editor exposes a predefined clickable palette");
console.log("POOPULATION smoke test: OK");
